version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: huihui
      POSTGRES_PASSWORD: huihui
      POSTGRES_DB: huihui-saas-control
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: huihui@hui.com
      PGADMIN_DEFAULT_PASSWORD: huihui
    ports:
      - "8080:80"
